[package]
name = "rdkafka-hang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdkafka = { version = "0.28", features = ["cmake-build", "ssl"] }
rdkafka-sys = "=4.2.0"
anyhow = "1.0"

